--- STEAMODDED HEADER
--- MOD_NAME: Google Translated
--- MOD_ID: googletranslated
--- MOD_AUTHOR: [Phrog]
--- MOD_DESCRIPTION: Google Translated all contexts
--- BADGE_COLOUR: 000000
--- DISPLAY_NAME: Google Translated 
--- PREFIX: GT
--- VERSION: 1.0.0
--- DEPENDENCIES: [Steamodded>=1.0.0~ALPHA-0812d]