[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]] 
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''
return string.format("%.3f",x/(10^fac))..'e'..fac'''
position = "before"
payload = '''
if num == math.huge then
    return "a lot"
end'''
match_indent = true